import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'primary': '#00658d',
                'on-primary': '#ffffff',
                'primary-container': '#00aeef',
                'on-primary-container': '#003e58',
                'inverse-primary': '#82cfff',
                'secondary': '#296195',
                'on-secondary': '#ffffff',
                'secondary-container': '#92c5fe',
                'on-secondary-container': '#115284',
                'tertiary': '#8d4f00',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#ea8c21',
                'on-tertiary-container': '#572f00',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'surface': '#f5faff',
                'on-surface': '#171c20',
                'surface-variant': '#dee3e8',
                'on-surface-variant': '#3e4850',
                'surface-dim': '#d6dae0',
                'surface-bright': '#f5faff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4fa',
                'surface-container': '#eaeef4',
                'surface-container-high': '#e4e9ee',
                'surface-container-highest': '#dee3e8',
                'surface-tint': '#00658d',
                'outline': '#6e7881',
                'outline-variant': '#bdc8d1',
                'inverse-surface': '#2c3135',
                'inverse-on-surface': '#ecf1f7',
                'background': '#f5faff',
                'on-background': '#171c20',
                'primary-fixed': '#c6e7ff',
                'primary-fixed-dim': '#82cfff',
                'on-primary-fixed': '#001e2d',
                'on-primary-fixed-variant': '#004c6b',
                'secondary-fixed': '#d0e4ff',
                'secondary-fixed-dim': '#9ccaff',
                'on-secondary-fixed': '#001d35',
                'on-secondary-fixed-variant': '#00497b',
                'tertiary-fixed': '#ffdcc0',
                'tertiary-fixed-dim': '#ffb876',
                'on-tertiary-fixed': '#2d1600',
                'on-tertiary-fixed-variant': '#6b3b00',
                'success': '#1e8f50',
                'on-success': '#ffffff',
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                'full': '9999px',
            },
            spacing: {
                'unit': '4px',
                'container-padding-mobile': '1rem',
                'container-padding-desktop': '2.5rem',
                'gutter': '1.5rem',
                'stack-sm': '0.5rem',
                'stack-md': '1rem',
                'stack-lg': '2rem',
            },
            fontFamily: {
                'display': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body': ['Inter', ...defaultTheme.fontFamily.sans],
                'label': ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
            },
            boxShadow: {
                'elevation-1': '0px 4px 20px rgba(0, 0, 0, 0.04)',
                'elevation-2': '0px 8px 30px rgba(0, 0, 0, 0.08)',
                'elevation-3': '0px 12px 40px rgba(0, 42, 124, 0.12)',
            },
        },
    },

    plugins: [forms],
};
